Importing python libraries for data cleaning

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Loading the dataset

In [2]:
customers = pd.read_csv('olist_customers_dataset.csv')  #customers dataset
orders = pd.read_csv('olist_orders_dataset.csv')   #orders dataset
items = pd.read_csv('olist_order_items_dataset.csv')     #order items dataset
products = pd.read_csv('olist_products_dataset.csv')    #products dataset
payments = pd.read_csv('olist_order_payments_dataset.csv')    #order payments dataset
reviews = pd.read_csv('olist_order_reviews_dataset.csv')     #order reviews dataset
sellers = pd.read_csv('olist_sellers_dataset.csv')     #sellers dataset
geo = pd.read_csv('olist_geolocation_dataset.csv')     #geolocation dataset
product_category_name = pd.read_csv('product_category_name_translation.csv')     #products category name in english translation

**Exploring the customers data for cleaning**

In [3]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

customer_id is different for every order, but customer_unique_id is unique for every customers

In [4]:
customers.duplicated().sum()

np.int64(0)

In [5]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [6]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [7]:
customers['customer_city'] = customers['customer_city'].str.title()

In [8]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP

**Exploring Orders Dataset for Cleaning**

In [9]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [10]:
orders['is_delayed'] = (orders['order_estimated_delivery_date']<orders['order_delivered_customer_date'])
orders['is_delayed'].sum()

np.int64(7827)

In [11]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
 8   is_delayed                     99441 non-null  bool
dtypes: bool(1), object(8)
memory usage: 6.2+ MB

Converting the date columns to datetime datatype

In [12]:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at']) 
orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

In [13]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   is_delayed                     99441 non-null  bool
dtypes: bool(1), datetime64[ns](5), object(3)
memory usage: 6.2+ MB

In [14]:
orders.duplicated().sum()

np.int64(0)

In [15]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
is_delayed                          0
dtype: int64

In [16]:
orders[orders['order_approved_at'].isna()]['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [17]:
orders.loc[(orders['order_status']=='delivered') & (orders['order_approved_at'].isna()), 'order_approved_at'] = orders['order_purchase_timestamp']

since the order_approved_at and order_purchase_timestamp both columns values are almost same so where items are delivered null values in order_approved_at are filled with order_purchase_timestamp values.

In [18]:
orders[orders['order_delivered_carrier_date'].isna()]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [19]:
orders[orders['order_delivered_customer_date'].isna()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

Rows with missing delivery timestamps represent cancelled, unavailable, or incomplete orders, if i drop these rows it could affect the delivery analysis so keeping these values null would be better

In [20]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_delayed
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False

**Exploring the Items Data for Cleaning**

In [21]:
items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [22]:
items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [23]:
items['shipping_limit_date'] = pd.to_datetime(items['shipping_limit_date'])

In [24]:
items.duplicated().sum()

np.int64(0)

In [25]:
items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

**Exploring the Products Data for Cleaning**

In [26]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [27]:
cols_to_drop = ['product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_length_cm', 'product_height_cm', 'product_width_cm']
products = products.drop(columns = cols_to_drop)

Dropped unnecessary columns

In [28]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32951 non-null  object
 1   product_category_name  32341 non-null  object
 2   product_weight_g       32949 non-null  float64
dtypes: float64(1), object(2)
memory usage: 772.4+ KB

In [29]:
products.duplicated().sum()

np.int64(0)

In [30]:
products.isnull().sum()

product_id                 0
product_category_name    610
product_weight_g           2
dtype: int64

filling the null values of product_weight_g by median value

In [31]:
products['product_weight_g'] = products['product_weight_g'].fillna(products['product_weight_g'].median())

we have an another dataset for category names

In [32]:
product_category_name.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [33]:
products = products.merge(product_category_name, how = 'left', on = 'product_category_name')
products

,product_id,product_category_name,product_weight_g,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,225.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1000.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,154.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,371.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,625.0,housewares
...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,12300.0,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1700.0,construction_tools_lights
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1400.0,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,700.0,computers_accessories
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,2083.0,bed_bath_table

In [34]:
products.drop(columns = ['product_category_name'], inplace = True)

In [35]:
products.rename(columns = {'product_category_name_english': 'product_category_name'}, inplace = True)

In [36]:
products.head()

                         product_id  product_weight_g product_category_name
0  1e9e8ef04dbcff4541ed26657ea517e5             225.0             perfumery
1  3aa071139cb16b67ca9e5dea641aaa2f            1000.0                   art
2  96bd76ec8810374ed1b65e291975717f             154.0        sports_leisure
3  cef67bcfe19066a932b7673e239eb23d             371.0                  baby
4  9dc1a7de274444849c219cff195d0b71             625.0            housewares

**Exploring the Payments Data for Cleaning**

In [37]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [38]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [39]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Creating new column for identify EMI purchases

In [40]:
def plan(value):
    if value == 1:
        return 'Full Payment'
    else:
        return 'EMI'

payments['payment_plan'] = payments['payment_installments'].apply(plan)
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value,payment_plan
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,EMI
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,Full Payment
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,Full Payment
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,EMI
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,EMI

**Exploring the Reviews Data for Cleaning**

In [41]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [42]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [43]:
null_pct1 = (reviews['review_comment_title'].isnull().sum() / len(reviews['review_comment_title'])) * 100
null_pct2 = (reviews['review_comment_message'].isnull().sum() / len(reviews['review_comment_message'])) * 100
null_pct1, null_pct2

(np.float64(88.34153027493349), np.float64(58.70253164556962))

The percentage of null values are very high, so dropping these columns would be better for analysis

In [44]:
cols_to_drop = ['review_comment_title', 'review_comment_message']
reviews = reviews.drop(columns = cols_to_drop)

Creating a new column for review type

In [45]:
def review(value):
    if value >=4:
        return 'Positive'
    elif value == 3:
        return 'Average'
    else:
        return 'Negative'
reviews['review_type'] = reviews['review_score'].apply(review)

Dropping unnecessary columns

In [46]:
cols = ['review_creation_date', 'review_answer_timestamp']
reviews.drop(columns =  cols, inplace = True)

In [47]:
reviews.head()

,review_id,order_id,review_score,review_type
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,Positive
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,Positive
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,Positive
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Positive
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Positive

**Exploring the Sellers data for cleaning**

In [48]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [49]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [50]:
sellers.duplicated().sum()

np.int64(0)

does not contain any null or duplicate values

In [51]:
sellers['seller_city'] = sellers['seller_city'].str.title()

because we have also converted city names to title form in customer dataset

**Exploring Geolocation data for Cleaning**

In [52]:
geo.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [53]:
geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [54]:
geo.duplicated().sum()

np.int64(261831)

In [55]:
geo[geo.duplicated()]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...
1000153,99970,-28.343273,-51.873734,ciriaco,RS
1000154,99950,-28.070493,-52.011342,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

these are 260k+ duplicate records in the dataset so removing these record would be better to eliminate reduntant entries.

In [56]:
geo.drop_duplicates(inplace = True)

In [57]:
geo.duplicated().sum()

np.int64(0)

In [58]:
geo['geolocation_city'] = geo['geolocation_city'].str.title()

In [59]:
geo.rename(columns = {'geolocation_lat':'latitude', 'geolocation_lng':'longitude'}, inplace = True)
geo.head()

,geolocation_zip_code_prefix,latitude,longitude,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,Sao Paulo,SP
1,1046,-23.546081,-46.644820,Sao Paulo,SP
2,1046,-23.546129,-46.642951,Sao Paulo,SP
3,1041,-23.544392,-46.639499,Sao Paulo,SP
4,1035,-23.541578,-46.641607,Sao Paulo,SP

**Creating connection for MySQL database to store the data and Run SQL query**

In [60]:
from sqlalchemy import create_engine

In [61]:
engine = create_engine('mysql+pymysql://root:6395@localhost/ecommerce')

the connection has been created with MySQL database name ecommerce

In [62]:
customers.to_sql('customers', con = engine, index = False, if_exists = 'replace')
orders.to_sql('orders', con = engine, index = False, if_exists = 'replace')
products.to_sql('products', con = engine, index = False, if_exists = 'replace')
items.to_sql('items', con = engine, index = False, if_exists = 'replace')
reviews.to_sql('reviews', con = engine, index = False, if_exists = 'replace')
payments.to_sql('payments', con = engine, index = False, if_exists = 'replace')
sellers.to_sql('sellers', con = engine, index = False, if_exists = 'replace')
geo.to_sql('geo', con = engine, index = False, if_exists = 'replace')

738332

Now the Data is Stored in MySQL Database and We can Run SQL Query on it

**Joining Tables**

In [63]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP

In [64]:
geo.head()

,geolocation_zip_code_prefix,latitude,longitude,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,Sao Paulo,SP
1,1046,-23.546081,-46.644820,Sao Paulo,SP
2,1046,-23.546129,-46.642951,Sao Paulo,SP
3,1041,-23.544392,-46.639499,Sao Paulo,SP
4,1035,-23.541578,-46.641607,Sao Paulo,SP

The geolocation table have multiple latitude and longitude for one zip_code_prefix, before joining these tables we have to grouby the data with Average latitude and Average longitude

In [65]:
query = '''
SELECT geolocation_zip_code_prefix, AVG(latitude) AS avg_lat, AVG(longitude) AS avg_lng, geolocation_state
FROM geo 
GROUP BY geolocation_zip_code_prefix, geolocation_state
'''

geo = pd.read_sql_query(query, con=engine)
geo.shape

(19023, 4)

In [66]:
customers = customers.merge(geo, how = 'left', left_on = 'customer_zip_code_prefix', right_on = 'geolocation_zip_code_prefix')

In [67]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,geolocation_zip_code_prefix,avg_lat,avg_lng,geolocation_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP,14409.0,-20.499273,-47.396658,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP,9790.0,-23.728396,-46.542250,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP,1151.0,-23.531309,-46.656690,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP,8775.0,-23.500670,-46.186348,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP,13056.0,-22.975708,-47.143140,SP

In [68]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99515 entries, 0 to 99514
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  99515 non-null  object
 1   customer_unique_id           99515 non-null  object
 2   customer_zip_code_prefix     99515 non-null  int64
 3   customer_city                99515 non-null  object
 4   customer_state               99515 non-null  object
 5   geolocation_zip_code_prefix  99237 non-null  float64
 6   avg_lat                      99237 non-null  float64
 7   avg_lng                      99237 non-null  float64
 8   geolocation_state            99237 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 6.8+ MB

In [69]:
customers.drop(columns = ['geolocation_zip_code_prefix', 'geolocation_state'], inplace = True)

In [70]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,avg_lat,avg_lng
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP,-20.499273,-47.396658
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP,-23.728396,-46.542250
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP,-23.531309,-46.656690
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP,-23.500670,-46.186348
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP,-22.975708,-47.143140

In [71]:
customers.isnull().sum()

customer_id                   0
customer_unique_id            0
customer_zip_code_prefix      0
customer_city                 0
customer_state                0
avg_lat                     278
avg_lng                     278
dtype: int64

We have some null values now, these are because some zip_code_prefix in customer table dont exist in geolocation table.
so lets fill these null values by mean after grouping.

In [72]:
customers['avg_lat'] = customers.groupby('customer_city')['avg_lat'].transform(lambda x: x.fillna(x.mean()))
customers['avg_lng'] = customers.groupby('customer_city')['avg_lng'].transform(lambda x: x.fillna(x.mean()))

In [73]:
customers.isnull().sum()

customer_id                  0
customer_unique_id           0
customer_zip_code_prefix     0
customer_city                0
customer_state               0
avg_lat                     52
avg_lng                     52
dtype: int64

We still have some null values because those cities have not coordinate data at all.
lets fill it by mean after grouping based on state

In [74]:
customers['avg_lat'] = customers.groupby('customer_state')['avg_lat'].transform(lambda x: x.fillna(x.mean()))
customers['avg_lng'] = customers.groupby('customer_state')['avg_lng'].transform(lambda x: x.fillna(x.mean()))

In [75]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
avg_lat                     0
avg_lng                     0
dtype: int64

Now the data is cleaned and ready to use.

In [76]:
customers.to_sql('customers', con = engine, index = False, if_exists = 'replace')

99515

In [77]:
pd.read_sql_query('select * from customers limit 5', con = engine)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,avg_lat,avg_lng
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP,-20.499273,-47.396658
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP,-23.728396,-46.542250
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP,-23.531309,-46.656690
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP,-23.500670,-46.186348
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP,-22.975708,-47.143140

**Joining the other tables**

In [78]:
pd.read_sql_query('select * from items limit 5', con = engine)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [79]:
pd.read_sql_query('select * from orders limit 5', con = engine)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_delayed
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0

In [80]:
pd.read_sql_query('select * from products limit 5', con = engine)

                         product_id  product_weight_g product_category_name
0  1e9e8ef04dbcff4541ed26657ea517e5             225.0             perfumery
1  3aa071139cb16b67ca9e5dea641aaa2f            1000.0                   art
2  96bd76ec8810374ed1b65e291975717f             154.0        sports_leisure
3  cef67bcfe19066a932b7673e239eb23d             371.0                  baby
4  9dc1a7de274444849c219cff195d0b71             625.0            housewares

In [81]:
pd.read_sql_query('select * from payments limit 5', con = engine)

,order_id,payment_sequential,payment_type,payment_installments,payment_value,payment_plan
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,EMI
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,Full Payment
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,Full Payment
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,EMI
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,EMI

In [82]:
pd.read_sql_query('select * from reviews limit 5', con = engine)

,review_id,order_id,review_score,review_type
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,Positive
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,Positive
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,Positive
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Positive
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Positive

In [83]:
pd.read_sql_query('select * from sellers limit 5', con = engine)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,Mogi Guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Rio De Janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,Sao Paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Braganca Paulista,SP

In [84]:
payments.shape

(103886, 6)

There are some order where customer used more than one payment_type for payment.

In [85]:
query = '''
SELECT order_id, SUM(payment_value) AS total_payment
FROM payments GROUP BY 
order_id
'''
payments = pd.read_sql_query(query, engine)
payments.to_sql('payments', con = engine, index = False, if_exists = 'replace')

99440

Joining the tables with items table to make a sales table.

In [95]:
query = '''
SELECT i.order_id, i.product_id, i.order_item_id, i.seller_id, i.price, i.freight_value,
o.customer_id, o.order_purchase_timestamp, o.order_delivered_customer_date, o.order_status, o.is_delayed,
r.review_type,
p.product_category_name, p.product_weight_g,
s.seller_zip_code_prefix, s.seller_city, s.seller_state,
pay.total_payment
FROM items AS i
LEFT JOIN orders AS o ON
i.order_id = o.order_id
LEFT JOIN products AS p ON
i.product_id = p.product_id
LEFT JOIN reviews AS r ON
i.order_id = r.order_id
LEFT JOIN sellers AS s ON
i.seller_id = s.seller_id
LEFT JOIN payments AS pay ON
i.order_id = pay.order_id
'''

sales = pd.read_sql_query(query, engine)

In [96]:
sales.head()

,order_id,product_id,order_item_id,seller_id,price,freight_value,customer_id,order_purchase_timestamp,order_delivered_customer_date,order_status,is_delayed,review_type,product_category_name,product_weight_g,seller_zip_code_prefix,seller_city,seller_state,total_payment
0,38035a76fee1437dca92e94b3e057af6,c6336fa91fbd87c359e44f5dca5a90ed,1,4c2b230173bb36f9b240f2b8ac11786e,45.90,14.10,c808210ff5bbf25415730cefb3ca0113,2018-02-23 09:35:40,2018-03-19 14:18:45,delivered,1,Positive,sports_leisure,150.0,3933,Sao Paulo,SP,60.00
1,344aec04212ff4fb3b73f86f50ad49b9,f883f9b139767a9577cdb99523c31d06,1,a416b6a846a11724393025641d4edd5e,49.90,11.15,59cc843769a7a0247161ebb5979f0e69,2018-05-18 10:56:51,2018-05-23 17:16:39,delivered,0,Positive,health_beauty,1150.0,3702,Sao Paulo,SP,61.05
2,ed0ae3732ee2e824f65323bc549605d9,154e7e31ebfa092203795c972e5804a6,1,cc419e0650a3c5ba77189a1882b7556a,23.99,15.10,9a26bc2f56790acd34d1ac7bd666fb56,2017-12-04 15:39:10,2017-12-12 17:58:32,delivered,0,Negative,health_beauty,100.0,9015,Santo Andre,SP,39.09
3,6e8e751584b3e3141e3e3c39f71408c2,6e423c2d28bfb207e1fd1d6e1df84721,2,289cdb325fb7e7f891c38608bf9e0962,28.89,30.77,85442da9cbd169529443a1d088a56346,2018-06-27 11:23:15,2018-07-11 23:34:40,delivered,0,Positive,perfumery,350.0,31570,Belo Horizonte,SP,187.15
4,51fb61776ef5371653e8b4e1c99d1c12,38b5079a807bb9f22ddfa46f929accee,1,6560211a19b47992c3666cc44a7e94c0,21.00,10.96,e2275acc246e2c5b85463018fac5cca9,2017-04-28 12:40:16,2017-05-17 10:04:47,delivered,0,Positive,perfumery,200.0,5849,Sao Paulo,SP,31.96

In [97]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113314 entries, 0 to 113313
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113314 non-null  object
 1   product_id                     113314 non-null  object
 2   order_item_id                  113314 non-null  int64
 3   seller_id                      113314 non-null  object
 4   price                          113314 non-null  float64
 5   freight_value                  113314 non-null  float64
 6   customer_id                    113314 non-null  object
 7   order_purchase_timestamp       113314 non-null  datetime64[ns]
 8   order_delivered_customer_date  110839 non-null  datetime64[ns]
 9   order_status                   113314 non-null  object
 10  is_delayed                     113314 non-null  int64
 11  review_type                    112372 non-null  object
 12  product_category_name          111678 non-null  object
 13  product_weight_g               113314 non-null  float64
 14  seller_zip_code_prefix         113314 non-null  int64
 15  seller_city                    113314 non-null  object
 16  seller_state                   113314 non-null  object
 17  total_payment                  113311 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(3), object(9)
memory usage: 15.6+ MB

In [98]:
sales.isnull().sum()

order_id                            0
product_id                          0
order_item_id                       0
seller_id                           0
price                               0
freight_value                       0
customer_id                         0
order_purchase_timestamp            0
order_delivered_customer_date    2475
order_status                        0
is_delayed                          0
review_type                       942
product_category_name            1636
product_weight_g                    0
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
total_payment                       3
dtype: int64

Null values in date columns shows that the orders are canceled, invoiced, unavailable, or shipped, If we fill these null values with random date or if we delete these rows it would affect analysis.
Some null values in review type shows that not every customers leave the rating for products, I will replace them with 'No Rating'.
Null values in product category name shows that some products that are ordered not exists in the products table, we will fill them with 'unknown', if i drop them it will affect the total revenue.
Total payment is just calculation of price + freight_value.

In [99]:
sales['review_type'] = sales['review_type'].fillna('No Rating')
sales['product_category_name'] = sales['product_category_name'].fillna('Unknown')
sales['total_payment'] = sales['total_payment'].fillna(sales['price'] + sales['freight_value'])

In [100]:
sales.isnull().sum()

order_id                            0
product_id                          0
order_item_id                       0
seller_id                           0
price                               0
freight_value                       0
customer_id                         0
order_purchase_timestamp            0
order_delivered_customer_date    2475
order_status                        0
is_delayed                          0
review_type                         0
product_category_name               0
product_weight_g                    0
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
total_payment                       0
dtype: int64

In [101]:
sales.duplicated().sum()

np.int64(485)

Now there are some duplicates values in the dataset, dropping them does not affect the sales.

In [102]:
sales.drop_duplicates(inplace = True)

In [103]:
sales.duplicated().sum()

np.int64(0)

Storing the Data in MySQL Database.

In [105]:
sales.to_sql('sales', con = engine, index = False, if_exists = 'replace')

112829

The data is Stored in SQL database and now We can run SQL query.

In [106]:
pd.read_sql_query('SELECT * FROM sales LIMIT 10', engine)

,order_id,product_id,order_item_id,seller_id,price,freight_value,customer_id,order_purchase_timestamp,order_delivered_customer_date,order_status,is_delayed,review_type,product_category_name,product_weight_g,seller_zip_code_prefix,seller_city,seller_state,total_payment
0,38035a76fee1437dca92e94b3e057af6,c6336fa91fbd87c359e44f5dca5a90ed,1,4c2b230173bb36f9b240f2b8ac11786e,45.90,14.10,c808210ff5bbf25415730cefb3ca0113,2018-02-23 09:35:40,2018-03-19 14:18:45,delivered,1,Positive,sports_leisure,150.0,3933,Sao Paulo,SP,60.00
1,344aec04212ff4fb3b73f86f50ad49b9,f883f9b139767a9577cdb99523c31d06,1,a416b6a846a11724393025641d4edd5e,49.90,11.15,59cc843769a7a0247161ebb5979f0e69,2018-05-18 10:56:51,2018-05-23 17:16:39,delivered,0,Positive,health_beauty,1150.0,3702,Sao Paulo,SP,61.05
2,ed0ae3732ee2e824f65323bc549605d9,154e7e31ebfa092203795c972e5804a6,1,cc419e0650a3c5ba77189a1882b7556a,23.99,15.10,9a26bc2f56790acd34d1ac7bd666fb56,2017-12-04 15:39:10,2017-12-12 17:58:32,delivered,0,Negative,health_beauty,100.0,9015,Santo Andre,SP,39.09
3,6e8e751584b3e3141e3e3c39f71408c2,6e423c2d28bfb207e1fd1d6e1df84721,2,289cdb325fb7e7f891c38608bf9e0962,28.89,30.77,85442da9cbd169529443a1d088a56346,2018-06-27 11:23:15,2018-07-11 23:34:40,delivered,0,Positive,perfumery,350.0,31570,Belo Horizonte,SP,187.15
4,51fb61776ef5371653e8b4e1c99d1c12,38b5079a807bb9f22ddfa46f929accee,1,6560211a19b47992c3666cc44a7e94c0,21.00,10.96,e2275acc246e2c5b85463018fac5cca9,2017-04-28 12:40:16,2017-05-17 10:04:47,delivered,0,Positive,perfumery,200.0,5849,Sao Paulo,SP,31.96
5,3f330c606a285a5bd1cf10b860dd6302,5f504b3a1c75b73d6151be81eb05bdc9,1,834f3294fba9f932f56edc879193f925,610.00,37.54,3dd397d7407cf9ab3713d1432a3759b6,2017-09-24 17:34:19,2017-09-29 19:22:25,delivered,0,Positive,cool_stuff,15350.0,14808,Araraquara,SP,647.54
6,27a7ac440630f9de788e4d66e72c6424,d696750e550fd0f733979dd7e5dff921,1,9de4643a8dbde634fe55621059d92273,169.99,16.40,5679e316d4dc59bd429d5851c36ed6c4,2017-04-21 21:38:07,2017-05-02 14:54:34,delivered,0,Positive,housewares,950.0,89225,Joinville,SC,186.39
7,d0fcb0e64631dcf3a108b1837a69d9a5,783caabd539c4079ec08423e30719fba,1,955fee9216a65b617aa5c0531780ce60,29.00,8.36,0a1ab2962856f2d5008692f7d6e22ce2,2018-08-09 20:54:56,2018-08-14 00:41:39,delivered,0,Positive,construction_tools_lights,500.0,4782,Sao Paulo,SP,37.36
8,5b7078954da6923760467cf39ac91bc0,5450ae624c196f64c291a61b12ffa3ee,1,5656537e588803a555b8eb41f07a944b,37.89,8.11,33a04ce7a2ad7df05942c7954e485a1c,2017-09-17 11:00:01,2017-09-19 18:11:40,delivered,0,Positive,computers_accessories,200.0,72015,Brasilia,DF,46.00
9,0bfa8870838091fe8171ed69f6b89fee,060c17562f97e5bb60bc0dfa4dd5b3f2,1,9f505651f4a6abe901a56cdc21508025,24.99,7.44,10f2beaf4d0f6f475d9f4cfdc9b05457,2018-08-22 10:21:13,2018-08-24 22:41:52,delivered,0,Positive,computers_accessories,150.0,4102,Sao Paulo,SP,64.86

**Summary**

In this notebook, we successfully cleaned, deduplicated, and raw Olist e-commerce dataset. By resolving complex multi-table joins and handling missing values, we made two highly optimized, analysis-ready tables customers and sales and exported them to a MySQL database.
Now the data is ready for Power BI dashboard.